### ISSUE TITLE
Windows 10 installation unclear

### ISSUE THREAD

**Issue by HypixelKing** [devanhurst/ktane_voice#17]
Multiple people have said this, noone understand how to install the windows 10 version, what do we have to do, what ruby to install bla bla bla

**Comment by BrunoMoreira99** [comment]
These issues about Windows are all duplicates of #8.
Unless someone already figured out how to compile Sphinxbase/Pocketsphinx libraries for Windows then it's currently not possible, we cannot install this on Windows because of those missing, required, libraries.

**Comment by devanhurst** [comment]
Not enough detail in this issue, but I'm working through all the old stuff now.
