### ISSUE TITLE
Decoder#unset_search failed with error code -1

### ISSUE THREAD

**Issue by apepindev** [devanhurst/ktane_voice#2]
When installing pocketsphinx-ruby as-is in the `GemFile`, the application will run then fail with the error `Decoder#unset_search failed with error code -1 (Pocketsphinx::API::Error)`. 

After finding out that this installs v0.3.0 and a commit was made afterwards to fix this, I added `gem 'pocketsphinx-ruby', :git => 'git://github.com/watsonbox/pocketsphinx-ruby.git', :ref => 'f2f562b'` in the `GemFile` but now it can't "require" it at all. 

`cannot load such file -- pocketsphinx-ruby (LoadError)`

My `gem env`:

```
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.5.1
  - RUBY VERSION: 2.2.3 (2015-08-18 patchlevel 173) [x86_64-darwin15]
  - INSTALLATION DIRECTORY: /Users/AndrewMac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0
  - RUBY EXECUTABLE: /Users/AndrewMac/.rbenv/versions/2.2.3/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/AndrewMac/.rbenv/versions/2.2.3/bin
  - SPEC CACHE DIRECTORY: /Users/AndrewMac/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/AndrewMac/.rbenv/versions/2.2.3/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-15
  - GEM PATHS:
     - /Users/AndrewMac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0
     - /Users/AndrewMac/.gem/ruby/2.2.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "install" => "--no-ri --no-rdoc"
     - "update" => "--no-ri --no-rdoc"
 - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/AndrewMac/.rbenv/versions/2.2.3/bin
     ...
```

**Comment by devanhurst** [comment]
I've been waiting for this error to be posted. Looking at the pocketsphinx-ruby repository, it seems that there was a commit that removed a Decoder.unset_search call that fixes this problem. However, that commit doesn't seem to have applied to the current version of the gem. Take a look at this commit: https://github.com/watsonbox/pocketsphinx-ruby/commit/6c0446ddb10b3106ed7a29136cd4c0b1c49f68d6

You'll have to navigate to that line in your local gem files, and delete it. Let me know how it goes.

**Comment by ashleypancho** [comment]
Had the same problem and followed those instructions. I'm still getting this error:
`/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- pocketsphinx-ruby (LoadError)
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from charlie.rb:1:in `<main>'`

**Comment by apepindev** [comment]
I actually did that soon after posting and I didn't come across any more errors. After brief use I couldn't get the application to respond to my voice, but I will try again soon. It'll likely be unrelated to this issue. Shall we keep this issue open until the `pocketsphinx-ruby` gem is updated?

Also, I think I've figured out why my git referenced gem couldn't be required. It was installed to `.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems` whereas all the other gems went to `.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems`. I probably have to include that to my gem paths.

**Comment by devanhurst** [comment]
Glad to hear you got it up and running, and thanks for all your work with these issue tickets! I opened an issue ticket on pocketsphinx-ruby, and I'm waiting to hear from them. It's a strange error... I feel like rubygems.org isn't tracking the most recent commits correctly, but that's just a guess.

**Comment by apepindev** [comment]
My pleasure. :) It certainly looks like rubygems.org only supply tagged releases and not the latest commit, which I guess is good in a way!

I'll properly test your app on my machine when I get back from work. I'm sure my colleagues won't appreciate me saying "bomb check" to my computer...

**Comment by devanhurst** [comment]
I've changed the command to "charlie bomb check", not like that makes it
any less weird.

**Comment by devanhurst** [comment]
@ashleypancho Did you ever end up seeing this error?

**Comment by apepindev** [comment]
Sorry, no I didn't in the end. Still relying on manually removing that line
in the pocketsphinx-ruby gem for now but it definitely fixes it.

**Comment by ashleypancho** [comment]
@devanhurst Yes, but it was fixed by that commit you mentioned, plus uninstalling/reinstalling bundle.

**Comment by apepindev** [comment]
@ashleypancho ah yes, I just got round to fixing that and raised a pull request.

**Comment by devanhurst** [comment]
Excellent, @Paradiddley!!
